name: CICD Dev

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

permissions:
  contents: read
  packages: read
  statuses: write
  id-token: write

env:
  _BUCKET: ${{ secrets.BUCKET }}
  _ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
  _PIPELINE_REPO: ${{ secrets.PIPELINE_REPO }}

jobs:
  ci:
    permissions: write-all
    name: Check code quality
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Super-linter
        uses: super-linter/super-linter@v6.6.0
        env:
          VALIDATE_PYTHON: true
          VALIDATE_PYTHON_BLACK: true
          VALIDATE_PYTHON_FLAKE8: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test:
    needs: [ci]
    name: Integration Tests
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 'Check Train Pipeline'
        uses: dorny/paths-filter@v2.2.1
        id: train-pipeline
        with:
            filters: |
                src:
                  - 'src/pipelines/pipelines/train/**'

      - name: 'Compile Pipeline: Train'
        if: steps.train-pipeline.outputs.src == 'true'
        run: |
          pip install --upgrade pip
          pip install -r src/requirements.txt
          python3 -B src/pipelines/pipelines/train/train_pipeline.py --compile
